/**
 * Error codes for the application
 * Organized by domain for better frontend handling and monitoring
 */

export const ERROR_CODES = {
  COMMON: {
    INTERNAL_ERROR: "INTERNAL_ERROR",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    NOT_FOUND: "NOT_FOUND",
    BAD_REQUEST: "BAD_REQUEST",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    RATE_LIMITED: "RATE_LIMITED",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
    TIMEOUT: "TIMEOUT",
  },

  AUTH: {
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    TOKEN_INVALID: "TOKEN_INVALID",
    SESSION_EXPIRED: "SESSION_EXPIRED",
    EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
    OAUTH_ERROR: "OAUTH_ERROR",
  },

  DATABASE: {
    DATABASE_ERROR: "DATABASE_ERROR",
    DATABASE_UNAVAILABLE: "DATABASE_UNAVAILABLE",
    UNIQUE_CONSTRAINT_FAILED: "UNIQUE_CONSTRAINT_FAILED",
    FOREIGN_KEY_CONSTRAINT_FAILED: "FOREIGN_KEY_CONSTRAINT_FAILED",
    TRANSACTION_FAILED: "TRANSACTION_FAILED",
  },

  EXTERNAL: {
    EXTERNAL_API_ERROR: "EXTERNAL_API_ERROR",
    EXTERNAL_API_TIMEOUT: "EXTERNAL_API_TIMEOUT",
    WEBHOOK_FAILED: "WEBHOOK_FAILED",
    THIRD_PARTY_UNAVAILABLE: "THIRD_PARTY_UNAVAILABLE",
    SYNC_FAILED: "SYNC_FAILED",
  },

  BUSINESS: {
    WORKSPACE_LIMIT_REACHED: "WORKSPACE_LIMIT_REACHED",
    BOOKMARK_ALREADY_EXISTS: "BOOKMARK_ALREADY_EXISTS",
    INVALID_FEED_URL: "INVALID_FEED_URL",
    RSS_SYNC_FAILED: "RSS_SYNC_FAILED",
  },
} as const;

export type ErrorCode =
  (typeof ERROR_CODES)[keyof typeof ERROR_CODES][keyof (typeof ERROR_CODES)[keyof typeof ERROR_CODES]];

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export type HttpStatus = (typeof HTTP_STATUS)[keyof typeof HTTP_STATUS];
