-- Audit trail for privileged access to user data.
--
-- Generated by `drizzle-kit generate --name add_audit_events`, with two
-- hand-spliced sections drizzle-kit cannot express (see docs/setup.md):
--   1. The audit_metadata_is_content_free() helper, created before the table
--      because the CHECK constraints below reference it.
--   2. The ENABLE ROW LEVEL SECURITY trailer.
--
-- Design constraints (see docs/policies/data-access.md §5):
--   * Append-only: no updated_at column, no trigger — the automated
--     updated_at machinery used by other tables is deliberately absent.
--     No repository code path ever issues UPDATE against this table.
--   * Content-free by STRUCTURE, not just convention: lib/audit.ts validates
--     every event before insert, and the CHECK constraints below mirror those
--     bounds so they hold for writers that bypass the module. Identity fields
--     match a machine-identifier grammar (no spaces, `/`, or `@` — so no
--     URLs, emails, paths, or prose); resource_id is UUID-only; every key and
--     value in metadata must be an identifier-like token.
--   * Sealed: RLS enabled with NO policies. anon/authenticated roles see zero
--     rows and cannot write. Only service-role connections (cron scripts via
--     lib/audit.ts) can read or write this table.

CREATE OR REPLACE FUNCTION public.audit_metadata_is_content_free(b jsonb)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
  SELECT bool_and(
    key !~ '[ @/]'
    AND CASE jsonb_typeof(value)
      WHEN 'array'  THEN public.audit_metadata_is_content_free(value)
      WHEN 'object' THEN public.audit_metadata_is_content_free(value)
      WHEN 'string' THEN value #>> '{}' !~ '[ @/]'
      ELSE true
    END
  )
  FROM jsonb_each(b);
$$;
--> statement-breakpoint
CREATE TABLE "audit_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"actor_type" text NOT NULL,
	"actor_id" text NOT NULL,
	"action" text NOT NULL,
	"resource_type" text NOT NULL,
	"resource_id" uuid,
	"reason" text NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
	CONSTRAINT "audit_events_actor_type_check" CHECK (actor_type IN ('cron', 'developer', 'system')),
	CONSTRAINT "audit_events_actor_id_check" CHECK (actor_id ~ '^[A-Za-z][A-Za-z0-9_:#.-]{0,199}$'),
	CONSTRAINT "audit_events_action_check" CHECK (char_length(action) <= 100 AND action ~ '^[a-z0-9]+([._][a-z0-9]+)*$'),
	CONSTRAINT "audit_events_resource_type_check" CHECK (resource_type ~ '^[a-z][a-z0-9_.-]{0,99}$'),
	CONSTRAINT "audit_events_reason_check" CHECK (char_length(reason) >= 3 AND char_length(reason) <= 500),
	CONSTRAINT "audit_events_metadata_content_check" CHECK (audit_metadata_is_content_free(metadata))
);
--> statement-breakpoint
CREATE INDEX "idx_audit_events_created_at" ON "audit_events" USING btree ("created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_audit_events_action" ON "audit_events" USING btree ("action");
--> statement-breakpoint
ALTER TABLE public.audit_events ENABLE ROW LEVEL SECURITY;

-- No RLS policies on purpose: this table is service-role-only.
